Repository mergestat/mergestat, pull requests merged in 2022-12, with the labels that each got.

#644 fix(syncer): do not append token to local URLs
  internal/syncer/syncer.go
Labels: bug, worker

#653 feat: implement `Yelp/detect-secrets` as another *experimental* repo scan type
  Dockerfile
  internal/syncer/syncer.go
  internal/syncer/yelp_detect_secrets_repo_scan.go
  migrations/900000000000013_add_yelp_detect_secrets_sync.down.sql
  migrations/900000000000013_add_yelp_detect_secrets_sync.up.sql
Labels: new sync type, worker, schema

#654 chore: updates some UI dependencies
  ui/package-lock.json
  ui/package.json
Labels: user interface, dependencies
